version: "3.1"

services:
  nginx:
    build: ./nginx
    depends_on:
      - api
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
  api:
    build: ./api
    environment:
      - NODE_ENV=development
      - DB_PATH=${DB_PATH}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    volumes:
      - "./api:/api"
    command: yarn run dev
    depends_on: 
      - db
  db:
    image: postgres:9.6-alpine
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=bastion
    volumes:
      - "./data/pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  migration:
    build:
      context: ./api
      dockerfile: Dockerfile.migration
    environment:
      - DB_PATH=${DB_PATH}
    volumes:
      - "./api:/api"
      - "/api/node_modules"
    depends_on: 
      - db