version: "3.1"

services:
  api:
    build: ./
    environment:
      - NODE_ENV=development
    volumes:
      - "./:/api"
      - "/api/node_modules"
    command: yarn run dev
    ports:
      - 3000:3000