version: "3.1"

services:
  api:
    build: ./
    environment:
      - NODE_ENV=development
      - DB_PATH=${DB_PATH}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - PORT=6969
    volumes:
      - "./:/api"
    command: yarn run dev
    ports:
      - 6969:6969
    depends_on: 
      - db
  db:
    image: postgres:9.6-alpine
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bastion
    volumes:
      - "./data/pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  migration:
    build:
      context: ./
      dockerfile: Dockerfile.migration
    environment:
      - DB_PATH=postgresql://postgres:password@db/bastion
    volumes:
      - "./:/api"
      - "/api/node_modules"
    depends_on: 
      - db